"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import styles from "../../commercial.module.css";
import { ALL_PARTNER_PLANS, PARTNER_ADDONS } from "@/lib/partner-os/catalog";
type Partner={id:string;display_name:string;partner_type:string;website:string|null;country:string|null;internal_status:string};
type Contact={id:string;full_name:string;email:string;role:string|null;is_primary:boolean};
type Activity={id:string;activity_type:string;summary:string;due_at:string|null;completed_at:string|null;created_at:string};
type Offer={id:string;offer_number:string;version:number;state:string;net_amount_cents:number;created_at:string};
type Campaign={id:string;partner_id:string;title:string;kind:string;starts_on:string;ends_on:string;status:string};
type Resource="partners"|"contacts"|"activities"|"offers"|"campaigns";
const types=[["hotel","Hotel"],["golf_club","Golfclub"],["destination","Destination"],["restaurant","Restaurant"],["experience","Erlebnis"],["other","Sonstige"]];
export default function PartnerManager(){
 const [partners,setPartners]=useState<Partner[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[activities,setActivities]=useState<Activity[]>([]),[offers,setOffers]=useState<Offer[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]);
 const [selected,setSelected]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [name,setName]=useState(""),[type,setType]=useState("hotel"),[country,setCountry]=useState(""),[website,setWebsite]=useState("");
 const [contactName,setContactName]=useState(""),[contactEmail,setContactEmail]=useState(""),[contactRole,setContactRole]=useState("");
 const [note,setNote]=useState(""),[activityType,setActivityType]=useState("note"),[due,setDue]=useState("");
 const [title,setTitle]=useState(""),[kind,setKind]=useState("launch"),[start,setStart]=useState(""),[end,setEnd]=useState("");
 const [offerNumber,setOfferNumber]=useState(""),[offerVersion,setOfferVersion]=useState(1),[offerTerms,setOfferTerms]=useState("");
 const [planId,setPlanId]=useState("essential"),[founding,setFounding]=useState(false),[addonIds,setAddonIds]=useState<string[]>([]);
 const chosenPlan=ALL_PARTNER_PLANS.find(p=>p.id===planId)!;
 const catalogTotal=(founding?chosenPlan.foundingPrice:chosenPlan.price)+PARTNER_ADDONS.filter(a=>addonIds.includes(a.id)).reduce((sum,a)=>sum+a.price,0);
 const load=useCallback(async(resource:Resource,partnerId?:string)=>{
  const url="/api/commercial/records?resource="+resource+(partnerId?"&partner_id="+encodeURIComponent(partnerId):"");
  const res=await fetch(url,{cache:"no-store"});if(!res.ok)throw new Error("Abruf fehlgeschlagen: "+resource+" ("+res.status+")");
  return (await res.json() as {records:unknown[]}).records;
 },[]);
 const reload=useCallback(async()=>{setLoading(true);try{setPartners(await load("partners") as Partner[]);setError("");}catch(e){setError(String(e));}finally{setLoading(false);}},[load]);
 useEffect(()=>{void reload();},[reload]);
 useEffect(()=>{if(!selected){setContacts([]);setActivities([]);setOffers([]);setCampaigns([]);return;}let live=true;Promise.all([load("contacts",selected),load("activities",selected),load("offers",selected),load("campaigns")]).then(([c,a,o,all])=>{if(live){setContacts(c as Contact[]);setActivities(a as Activity[]);setOffers(o as Offer[]);setCampaigns((all as Campaign[]).filter(e=>e.partner_id===selected));}}).catch(e=>{if(live)setError(String(e));});return()=>{live=false;};},[selected,load]);
 async function save(body:Record<string,unknown>,success:string){
  setBusy(true);setError("");setNotice("");
  try{const res=await fetch("/api/commercial/records",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await res.json() as {record?:{id:string};error?:string};if(!res.ok)throw new Error(result.error||"Speichern fehlgeschlagen");setNotice(success);await reload();if(body.resource==="partners"&&result.record)setSelected(result.record.id);else if(selected){const [c,a,o,all]=await Promise.all([load("contacts",selected),load("activities",selected),load("offers",selected),load("campaigns")]);setContacts(c as Contact[]);setActivities(a as Activity[]);setOffers(o as Offer[]);setCampaigns((all as Campaign[]).filter(e=>e.partner_id===selected));}return true;}catch(e){setError(String(e));return false;}finally{setBusy(false);}
 }
 async function patch(body:Record<string,unknown>){setBusy(true);setError("");try{const res=await fetch("/api/commercial/records",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!res.ok){const j=await res.json() as {error?:string};throw new Error(j.error||"Aktualisierung fehlgeschlagen");}if(selected){const [a,all]=await Promise.all([load("activities",selected),load("campaigns")]);setActivities(a as Activity[]);setCampaigns((all as Campaign[]).filter(e=>e.partner_id===selected));}}catch(e){setError(String(e));}finally{setBusy(false);}}
 const active=partners.find(p=>p.id===selected);
 return <main className={styles.page}><div className={styles.wrap}><header className={styles.head}><div><div className={styles.eyebrow}>AROUND / COMMERCIAL DESK / PRIVATE</div><h1>Partner<br/>Operations<span style={{color:"#93b52b"}}>.</span></h1><p>Echte Partner, Kontakte, Angebote, Aktivitäten und Terminwünsche. Nur für autorisierte AROUND-Operatoren.</p></div><span className={styles.pill}>PRIVATE · LIVE DATA</span></header>
 <nav className={styles.toolNav}><Link href="/commercial/live">Anfragen</Link><strong>Partnerverwaltung</strong><Link href="/commercial/live/calendar">Live Calendar</Link></nav>
 {error&&<p role="alert" className={styles.operatorError}>{error}</p>}{notice&&<p role="status" className={styles.operatorNotice}>{notice}</p>}
 <div className={styles.layout}><section className={styles.board}><div className={styles.formStack}><div className={styles.eyebrow}>PARTNER ANLEGEN</div><label>Unternehmen<input value={name} onChange={e=>setName(e.target.value)} placeholder="Name des Unternehmens"/></label><label>Typ<select value={type} onChange={e=>setType(e.target.value)}>{types.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Land / Region<input value={country} onChange={e=>setCountry(e.target.value)}/></label><label>Website<input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://…"/></label><button className={styles.action} disabled={busy||name.trim().length<2} onClick={async()=>{if(await save({resource:"partners",display_name:name,partner_type:type,country:country||null,website:website||null},"Partner gespeichert.")){setName("");setCountry("");setWebsite("");}}}>PARTNER SPEICHERN ↗</button></div><div className={styles.sectionTitle} style={{padding:"20px 28px"}}><h2>Deine Partner</h2><span>{partners.length}</span></div>{loading?<p className={styles.empty}>Lade Partner …</p>:partners.length===0?<p className={styles.empty}>Noch keine Partner erfasst.</p>:partners.map(p=><button key={p.id} className={styles.task} onClick={()=>setSelected(p.id)} style={{background:selected===p.id?"#dce9bf":undefined}}><span>↗</span><span><strong>{p.display_name}</strong><small>{p.partner_type} · {p.internal_status}</small></span><b>ÖFFNEN</b></button>)}</section>
 <aside className={styles.side}>{!active?<><div className={styles.eyebrow}>PARTNER DETAIL</div><h3>Partner auswählen.</h3><p>Wähle links einen Partner oder lege einen neuen an.</p></>:<><div className={styles.eyebrow}>PARTNER DETAIL</div><h3>{active.display_name}</h3><p className={styles.muted}>{active.partner_type} · {active.country||"Land offen"}</p>{active.website&&<a href={active.website} target="_blank" rel="noopener noreferrer">WEBSITE ↗</a>}
 <div className={styles.detail}><strong>Kontakte ({contacts.length})</strong>{contacts.map(c=><p key={c.id}>{c.full_name} {c.is_primary?"★":""}<br/><a href={`mailto:${c.email}`}>{c.email}</a>{c.role?" · "+c.role:""}</p>)}<label className={styles.operatorField}>Name<input value={contactName} onChange={e=>setContactName(e.target.value)}/></label><label className={styles.operatorField}>E-Mail<input type="email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)}/></label><label className={styles.operatorField}>Funktion<input value={contactRole} onChange={e=>setContactRole(e.target.value)}/></label><button className={styles.action} disabled={busy||!contactName||!contactEmail} onClick={async()=>{if(await save({resource:"contacts",partner_id:selected,full_name:contactName,email:contactEmail,role:contactRole||null,is_primary:contacts.length===0},"Kontakt gespeichert.")){setContactName("");setContactEmail("");setContactRole("");}}}>KONTAKT HINZUFÜGEN</button></div>
 <div className={styles.detail}><strong>Aktivitäten ({activities.length})</strong>{activities.map(a=><p key={a.id}><b>{a.activity_type}</b> · {a.summary}<br/><small>{a.due_at?"Fällig: "+new Date(a.due_at).toLocaleDateString("de-DE"):""} {a.completed_at?"✓ Erledigt":""}</small>{!a.completed_at&&<button className={styles.operatorInline} disabled={busy} onClick={()=>void patch({resource:"activities",id:a.id})}>Als erledigt markieren</button>}</p>)}<label className={styles.operatorField}>Typ<select value={activityType} onChange={e=>setActivityType(e.target.value)}>{["note","call","email","meeting","task","follow_up"].map(t=><option key={t} value={t}>{t}</option>)}</select></label><label className={styles.operatorField}>Notiz / Aufgabe<textarea value={note} onChange={e=>setNote(e.target.value)} rows={3}/></label><label className={styles.operatorField}>Wiedervorlage (optional)<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><button className={styles.action} disabled={busy||!note.trim()} onClick={async()=>{if(await save({resource:"activities",partner_id:selected,activity_type:activityType,summary:note,due_at:due?due+"T12:00:00Z":null},"Aktivität gespeichert.")){setNote("");setDue("");}}}>AKTIVITÄT SPEICHERN</button></div>
 <div className={styles.detail}><strong>Angebote ({offers.length})</strong>{offers.map(o=><p key={o.id}>{o.offer_number} / V{o.version} · {o.state}<br/>{(o.net_amount_cents/100).toLocaleString("de-DE",{style:"currency",currency:"EUR"})} Katalogwert (Entwurf)</p>)}<p className={styles.muted}>Nur interne Angebotsentwürfe; kein Versand und keine Annahme.</p><label className={styles.operatorField}>Angebotsnummer<input value={offerNumber} onChange={e=>setOfferNumber(e.target.value)}/></label><label className={styles.operatorField}>Version<input type="number" min={1} value={offerVersion} onChange={e=>setOfferVersion(Number(e.target.value))}/></label><label className={styles.operatorField}>AROUND Paket<select value={planId} onChange={e=>setPlanId(e.target.value)}>{ALL_PARTNER_PLANS.map(p=><option key={p.id} value={p.id}>{p.name} · {p.price.toLocaleString("de-DE")} € / Jahr</option>)}</select></label><label className={styles.operatorCheck}><input type="checkbox" checked={founding} onChange={e=>setFounding(e.target.checked)}/> Founding-Partner-Preis verwenden</label><div className={styles.operatorField}><strong>Optionale Leistungen</strong>{PARTNER_ADDONS.map(a=><label className={styles.operatorCheck} key={a.id}><input type="checkbox" checked={addonIds.includes(a.id)} onChange={e=>setAddonIds(current=>e.target.checked?[...current,a.id]:current.filter(id=>id!==a.id))}/>{a.name} · {a.price} €</label>)}</div><p className={styles.operatorTotal}>Katalogsumme: <strong>{catalogTotal.toLocaleString("de-DE",{style:"currency",currency:"EUR"})}</strong></p><p className={styles.muted}>Interner Katalogentwurf. Steuerliche Behandlung und verbindliche Angebotsbedingungen vor Versand klären.</p><label className={styles.operatorField}>Konditionsversion (optional)<input value={offerTerms} onChange={e=>setOfferTerms(e.target.value)}/></label><button className={styles.action} disabled={busy||!offerNumber||!Number.isInteger(offerVersion)||offerVersion<1} onClick={async()=>{if(await save({resource:"offers",partner_id:selected,offer_number:offerNumber,version:offerVersion,net_amount_cents:catalogTotal*100,line_items:[],catalog_snapshot:{source:"around_catalog",plan_id:planId,founding,addon_ids:addonIds},terms_version:offerTerms||null},"Angebotsentwurf gespeichert.")){setOfferNumber("");setOfferTerms("");setAddonIds([]);}}}>ENTWURF SPEICHERN</button></div>
 <div className={styles.detail}><strong>Launches & Packages ({campaigns.length})</strong>{campaigns.map(c=><p key={c.id}><b>{c.title}</b> · {c.kind}<br/>{c.starts_on} – {c.ends_on}<br/><small>{c.status}</small>{c.status==="requested"&&<><button className={styles.operatorInline} disabled={busy} onClick={()=>void patch({resource:"campaigns",id:c.id,status:"confirmed"})}>Termin bestätigen</button><button className={styles.operatorInline} disabled={busy} onClick={()=>void patch({resource:"campaigns",id:c.id,status:"cancelled"})}>Absagen</button></>}{c.status==="confirmed"&&<button className={styles.operatorInline} disabled={busy} onClick={()=>void patch({resource:"campaigns",id:c.id,status:"active"})}>Als aktiv markieren</button>}{c.status==="active"&&<button className={styles.operatorInline} disabled={busy} onClick={()=>void patch({resource:"campaigns",id:c.id,status:"completed"})}>Abschließen</button>}</p>)}<label className={styles.operatorField}>Titel<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className={styles.operatorField}>Art<select value={kind} onChange={e=>setKind(e.target.value)}>{["launch","package","campaign"].map(k=><option key={k} value={k}>{k}</option>)}</select></label><label className={styles.operatorField}>Start<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className={styles.operatorField}>Ende<input type="date" min={start} value={end} onChange={e=>setEnd(e.target.value)}/></label><button className={styles.action} disabled={busy||!title||!start||!end||end<start} onClick={async()=>{if(await save({resource:"campaigns",partner_id:selected,title,kind,starts_on:start,ends_on:end},"Terminwunsch gespeichert.")){setTitle("");setStart("");setEnd("");}}}>TERMINWUNSCH SPEICHERN</button></div>
 </>}</aside></div><footer className={styles.foot}><p className={styles.muted}>Privater interner Arbeitsbereich. Angebotsentwürfe und Terminbestätigungen lösen weder Vertragsschluss noch Sanity-Publikation oder E-Mail aus.</p></footer></div></main>;
}